# Generated by Django 5.1.1 on 2024-09-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n_app', '0004_newspost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
