# Generated by Django 5.1.1 on 2024-09-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n_app', '0006_postlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
