# Generated by Django 5.1.1 on 2024-09-20 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_app', '0007_delete_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n_app.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n_app.myusers')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
