# Generated by Django 5.1.1 on 2024-09-20 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_app', '0008_postliked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='n_app.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n_app.myusers')),
            ],
        ),
    ]
